name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Set up python
        run: |
          python -m pip install --upgrade pip
          pip install flask flask-cors pymongo python-dotenv 

      - name: Start Flask App in Background
        env: 
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          # nohup keeps the process running; > directs our logs (Good for debugging) 
          nohup python run.py > flask_log.txt 2>&1 &

      - name: Wait for Flask to start
        run: sleep 5
      
      - name: Run tests
        env:
          FLASK_URL: https://127.0.0.1:5000
        run: npm test
